# Generated by Django 4.1.7 on 2023-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_crypto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="crypto",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Crypto",
        ),
    ]
