# Generated by Django 4.1.7 on 2023-03-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cryptoIds',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
