# Generated by Django 4.1.7 on 2023-03-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_crypto", "0002_alter_portfolio_crypto_delete_crypto"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="name",
            field=models.TextField(null=True),
        ),
    ]
