# Generated by Django 4.1.7 on 2023-03-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_crypto', '0002_alter_portfolio_cryptoids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cryptoIds',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
