# Generated by Django 4.1.7 on 2023-03-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_crypto", "0004_remove_portfolio_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="name",
            field=models.TextField(default="Portfolio"),
        ),
    ]
