# Generated by Django 4.1.7 on 2023-03-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_crypto", "0005_alter_portfolio_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="totalBalance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
