# Generated by Django 4.1.7 on 2023-03-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_crypto", "0006_portfolio_totalbalance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="crypto",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="cryptoIds",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
