# Generated by Django 4.1.7 on 2023-03-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_crypto", "0007_remove_portfolio_crypto_portfolio_cryptoids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="cryptoIds",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
